/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ClientClientImport } from './routes/client/client'

// Create/Update Routes

const ClientClientRoute = ClientClientImport.update({
  id: '/client/client',
  path: '/client/client',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/client/client': {
      id: '/client/client'
      path: '/client/client'
      fullPath: '/client/client'
      preLoaderRoute: typeof ClientClientImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/client/client': typeof ClientClientRoute
}

export interface FileRoutesByTo {
  '/client/client': typeof ClientClientRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/client/client': typeof ClientClientRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/client/client'
  fileRoutesByTo: FileRoutesByTo
  to: '/client/client'
  id: '__root__' | '/client/client'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ClientClientRoute: typeof ClientClientRoute
}

const rootRouteChildren: RootRouteChildren = {
  ClientClientRoute: ClientClientRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/client/client"
      ]
    },
    "/client/client": {
      "filePath": "client/client.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
